### ISSUE TITLE
Web extensio not working anymore

### ISSUE THREAD

**Issue by klein0r** [ioBroker/ioBroker.rest-api#145]
**Describe the bug**  

I'm using the following URL to set a state via api (works with version 2.0.3):

```
http://10.10.2.51:8082/rest-api/v1/state/0_userdata.0.contact.doorbell?value=true
```

```
Cannot start extension "rest-api.0": Error: Cannot find module 'iobroker.rest-api/lib/rest-api.js' Require stack:- /opt/iobroker/node_modules/iobroker.web/dist/main.js
```

**Expected behavior**  

State will be set

**Screenshots & Logfiles**  

Since version 3.0.0, this request returns an html page:

<img width="766" alt="Image" src="https://github.com/user-attachments/assets/21a2f000-1878-4ff1-bc42-cbd3f5cd0f57" />

<img width="674" alt="Image" src="https://github.com/user-attachments/assets/ad649033-b838-48b7-9eb6-5e9440cddc54" />

**Versions:**  
 - Adapter version: 3.0.0
 - JS-Controller version: 7.0.7
 - Node version: v20.19.0
 - Operating system: Debian 12

**Comment by klein0r** [comment]
Looks like the path is incomplete (missing `dist` folder)

https://github.com/ioBroker/ioBroker.rest-api/blob/f416949c207fc90da479348ccded2ace7566df5a/io-package.json#L121

**Comment by Marc-Berg** [comment]
I can't get the requests to work via the web extension with Version 3.0.1. Which request would be correct

/rest/ (as in the readme)
/rest-api/
/rest-api/v1/

?

None of the URLs work, all of them return a 404 error.

**Comment by SimonFischer04** [comment]
Same issue here.

> I can't get the requests to work via the web extension with Version 3.0.1. Which request would be correct
> 
> /rest/ (as in the readme) /rest-api/ /rest-api/v1/
> 
> ?
> 
> None of the URLs work, all of them return a 404 error.


At least /rest-api/v1/state would be the one that gets called using the swagger-ui

**Comment by SimonFischer04** [comment]
@klein0r how have you solved it?
I still have the same issue.

**Comment by SimonFischer04** [comment]
I'm a bit confused now.
Did it work for you @klein0r or why did you close the issue before reopening it.

Obviously something should be fixed, as @GermanBluefox commited something referencing this issue.

Maybe it's just some version issue with rest-api adapter, web adapter, js-controller?
